### ISSUE TITLE
Error SpeechRecognition is not defined when using with angular4, cordova and android

### ISSUE THREAD

**Issue by lokeshdaiya** [macdonst/SpeechRecognitionPlugin#104]
1. I have installed your plugin
2, Added statement `declare var SpeechRecognition:any;`
3. Initialized as below
```
 this.recognition = new SpeechRecognition();
    this.recognition.onresult = (event)=> {
      console.log(this.el.nativeElement.querySelectorAll(".content")[0]);
      this.el.nativeElement.querySelectorAll(".content")[0].innerText = event.results[0][0].transcript
      
    };
```
I followed this thread https://forum.ionicframework.com/t/something-different-in-rc3-4-vs-rc2-in-declaration/73590  but still getting error

**Comment by mathildebuenerd** [comment]
Have you finally found a solution to resolve this error ? I have the same one with cordova and android. Thanks

**Comment by macdonst** [comment]
@lokeshdaiya what is the error you are getting?

**Comment by arun02** [comment]
Error SpeechRecognition is not defined - have someone found a solution for this.

**Comment by lokeshdaiya** [comment]
I was getting that error on mobile only and reason was I have to give permission for recording for that app.
