### ISSUE TITLE
help me please. I can not figure out how to install the Russian language. How to do it?

### ISSUE THREAD

**Issue by reanimator53** [macdonst/SpeechRecognitionPlugin#105]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-speech-recognition   # e.g. 1.5.3

**Comment by jcesarmobile** [comment]
you can't install languages, you just can use whatever the system supports.
For iOS 10 and greater, Russian is supported with ru-RU code.
For Android, no idea if it's supported.

**Comment by reanimator53** [comment]
How can I change the default language?
