### ISSUE TITLE
How can I change the default language?

### ISSUE THREAD

**Issue by reanimator53** [macdonst/SpeechRecognitionPlugin#106]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-speech-recognition   # e.g. 1.5.3

**Comment by jcesarmobile** [comment]
This plugin uses the Web Speech API Specification (https://w3c.github.io/speech-api/speechapi.html). So, read their docs.
