### ISSUE TITLE
Add support to browser for chrome ( & other browsers)

### ISSUE THREAD

**Issue by tryadelion** [macdonst/SpeechRecognitionPlugin#107]
### Expected Behaviour
SpeechRecognition() should work correctly on google chrome.
### Actual Behaviour
throws nasty errors:

Error: exec proxy not found for :: SpeechRecognition :: init SpeechRecognition.js:35
 error: Missing Command Error home.ts:69
cordova.js:1003 Error: exec proxy not found for :: SpeechRecognition :: start 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Chrome Version 59.0.3071.86 (Build) (64 bits)

**Comment by macdonst** [comment]
@tryadelion give 0.3.0 a try from NPM in Chrome. It should work now without the above errors.

**Comment by tryadelion** [comment]
i've dowloaded the latest (0.3.0) version and it keeps throwing the same issues:
Error: exec proxy not found for :: SpeechRecognition :: init
Error: exec proxy not found for :: SpeechRecognition :: start

i tried cleaning up the node_modules folder, rebuilding the whole thing, and building for prod.
Sorry  for the inconvenience.

**Comment by macdonst** [comment]
It seems @tryadelion fixed this by removing and adding the platform.
