### ISSUE TITLE
iOS fresh install troubles

### ISSUE THREAD

**Issue by LukePulverenti** [macdonst/SpeechRecognitionPlugin#11]
The build fails with two issues:

- Looking for ResourcesiSpeechSDK.bundle when it should be Resources/iSpeechSDK.bundle

- Similarly, it's looking for Pluginsorg.apache...libSpeechSDK.a when it should be Plugins/org.apache.../libSpeechSDK.a

After fixing these two paths it builds fine.

**Comment by jcesarmobile** [comment]
Can you provide more details (cordova version, device where you tested, etc) and steps to reproduce?

I've just created a new project with cordova 5.0 (iOS 3.8.0), installed the plugin and the project built without errors

**Comment by LukePulverenti** [comment]
same versions. i suppose if it builds fine on a fresh project than we can close this. my project already has a number of plugins and i've had to make manual changes along the way so perhaps that's what threw off the code that attempts to add the paths to the project.
