### ISSUE TITLE
Response in IOS is very slow compare to android

### ISSUE THREAD

**Issue by Gamerakki** [macdonst/SpeechRecognitionPlugin#115]
### Expected Behaviour
The text to speech should very fast in IOS but its not... But in Android its working smoothly with a fast response
### Actual Behaviour
The response in both platform should be same
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android: 8.0
IOS: 11.2
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
MI A1
#### Cordova CLI version and cordova platform version

    cordova --version : 8.0.0                                   # e.g. 6.0.0
    cordova platform version android : 7.1.0                     # e.g. 4.1.1
    cordova platform version ios : 4.5.4                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-speech-recognition: 0.3.0   # e.g. 1.5.3

**Comment by jcesarmobile** [comment]
Sorry about that, but it's as fast as it can be using Apple provided SDKs and we can't improve it, only Apple can, so consider reporting it in Apple's bug tracker.

Try enabling partial results, I think that should have faster response

**Comment by Gamerakki** [comment]
Hii can you tell how to enable that partial results?

**Comment by jcesarmobile** [comment]
Read the Speech API https://w3c.github.io/speech-api/speechapi.html

It should be the part about interimResults
