### ISSUE TITLE
Error installing the plugin cordova 7

### ISSUE THREAD

**Issue by Stan801003A** [macdonst/SpeechRecognitionPlugin#118]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 7.1.0
    cordova platform version android                     # e.g. 6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-speech-recognition   # e.g. 1.5.3

I am trying to install the plugin but keep getting the following errors:

$ cordova plugin add https://github.com/macdonst/SpeechRecognitionPlugin
Error: Failed to fetch plugin https://github.com/macdonst/SpeechRecognitionPlugin via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

**Comment by jcesarmobile** [comment]
This isn’t a bug in the plugin, probably Cordova or environment problem
