### ISSUE TITLE
Uncaught ReferenceError: SpeechRecognition is not defined

### ISSUE THREAD

**Issue by logalleg** [macdonst/SpeechRecognitionPlugin#12]
I keep receiving the error "Uncaught ReferenceError: SpeechRecognition is not defined" when I try to initialize a new SpeechRecognition object.

My code is failing on the first line inside this function:

<pre>
function initSpeechRecognition() {
    recognition = new SpeechRecognition(); // failing here, note: recognition is a global variable
    recognition.onresult = function(event) {
        if (event.results.length > 0) {
            // TODO
        }
    };
}
</pre>
Any thoughts?

**Comment by jcesarmobile** [comment]
Are you waiting for the device ready event before calling the new SpeechRecognition();?

**Comment by logalleg** [comment]
Oops. I had my Cordova app variable defined incorrectly so device ready was being fired at the wrong time. Thanks haha.
