### ISSUE TITLE
Fails on iOS

### ISSUE THREAD

**Issue by hashg** [macdonst/SpeechRecognitionPlugin#13]
I have adding the plugin speechrecognitionplugin and org.apache.cordova.media.
Still it keeps failing with this error - 
> "306 : Unable to start an audio queue. Can happen when another audio queue has higher precedence than ours does."

**Comment by jcesarmobile** [comment]
Can you share a code example where you get the error?

**Comment by hashg** [comment]
I started from scratch and just added speechplugin. It works fine without any issues. Closing it.
