### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by patrickpereira** [macdonst/SpeechRecognitionPlugin#14]
Hi!

Great plugin!

The Android version works alot better than the iOS version, what SDK is used in the Android is it possible to use the same in the iOS version?

BR Patrick

**Comment by jcesarmobile** [comment]
Android uses android's native speech recognizer ( http://developer.android.com/reference/android/speech/SpeechRecognizer.html ), so no, I can't use the same in the iOS version. If you know a better SDK for iOS speech recognition let me know.

**Comment by davidxie** [comment]
I am new to this area.
Why can't you use Google speech-to-text API. 
Here is a project sample for doing in that way.

**Comment by jcesarmobile** [comment]
I've read this caveats:

Here are a few caveats you have to know about, should you decide to use this API in a production environment. (I don't recommend it)

    The API only accepts up to ~10-15 seconds of audio.
    Generating your own Speech API Key, you can only make 50 requests per day.


So I don't think it's suitable
