### ISSUE TITLE
Not working on android kitkat

### ISSUE THREAD

**Issue by rkjamvi** [macdonst/SpeechRecognitionPlugin#16]
Hi Sam,

I am using Adobe build to make android apk. 

I put below line to include plugin in config.xml but when i submit code there, it gives error of invalid plugin.

<gap:plugin name="org.apache.cordova.speech.SpeechRecognition" />

and in my index.html i used your sample code to test.

 <script type="text/javascript">
    var recognition = new SpeechRecognition();
    recognition.onresult = function(event) {
      if (event.results.length > 0) {
        q.value = event.results[0][0].transcript;
        q.form.submit();
      }
    }
  </script>

  <form action="http://www.example.com/search">
    <input type="search" id="q" name="q" size=60>
    <input type="button" value="Click to Speak" onclick="recognition.start()">
  </form>

I also tried below plugin but its not showing/starting voice mic etc
https://build.phonegap.com/plugins/2834

Best regards,
Rizwan

**Comment by jcesarmobile** [comment]
The plugin isn't avaiable for phonegap build, see this related issue
https://github.com/macdonst/SpeechRecognitionPlugin/issues/9
