### ISSUE TITLE
Plugin not working on intel xdk

### ISSUE THREAD

**Issue by lucianogime** [macdonst/SpeechRecognitionPlugin#17]
It is not working using intel xdk android crosswalk. I have tried the basic example and nothing happens.

**Comment by jcesarmobile** [comment]
Do you see any error on logcat?

**Comment by lucianogime** [comment]
It does not show any error.. But when i run it on my phone It just doens't work.. Have tried? Did it work for you? Which Building tool are you using?

**Comment by lucianogime** [comment]
It is working now, anyway thanks for replying!

**Comment by jcesarmobile** [comment]
Did you do something to make it work?
