### ISSUE TITLE
SpeechRecognition on Adobe Build

### ISSUE THREAD

**Issue by rkjamvi** [macdonst/SpeechRecognitionPlugin#19]
Hi Sam,

I am developing an app which uses Speech recognition and need plugin available on Adobe build, If i pay membership fee, will you upload that?

It will be great help to complete this app.

Thanks and regards,
Rizwan

**Comment by jcesarmobile** [comment]
If you pay the membership you can download the code and upload the plugin as private plugin for your use only, but change the plugin id on the plugin.xml file, so if @macdonst wants to upload it some day he has no problems
