### ISSUE TITLE
how do I get the audio file generated?

### ISSUE THREAD

**Issue by TD-Solutions** [macdonst/SpeechRecognitionPlugin#23]
Hello, for my app I need to be able to access for external storage the audio file that was generated along the process. Is there a way to get it? Thx

**Comment by jcesarmobile** [comment]
No, it's not possible and won't be possible as the plugin intends to follow the w3c API specification and getting the audio file isn't on the API

**Comment by TD-Solutions** [comment]
Thank you Julio for your quick answer. Would you have any idea of a workaround though ? Do you know of an api/service that would take an audio file for input and not an audio stream ?


Thank you very much for your help.


Regards,


T


Sent by Outlook for Android





On Wed, Sep 16, 2015 at 12:26 PM -0700, "Julio César" <notifications@github.com> wrote:
No, it's not possible and won't be possible as the plugin intends to follow the w3c API specification and getting the audio file isn't on the API

---

**Comment by jcesarmobile** [comment]
I've seen people using some google private API service where you can send the audio file and they return the recognized text (I think it's the one they use on chrome)

**Comment by TD-Solutions** [comment]
thx julio! will look into it.

T


Thierry DANSE| Manager | TD-Solutions | http://www.td-solutions.com

Mobile: +33 6 62 21 00 94 | Mail: td@td-solutions.com | 16 rue du Grand Prieuré 75011 PARIS, France______________________________________________________________________

This
 electronic mail transmission is confidential, may be priviledged and 
should be read or retained only 
by the intended recipient. It shall not
 deemed to be binding unless confirmed in writing by separate
instrument
 by a duly authorized representative of the Company.


Date: Sun, 20 Sep 2015 11:59:33 -0700
