### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by stefano055415** [macdonst/SpeechRecognitionPlugin#3]
ios only works for English?

**Comment by siyanbendan** [comment]
are you sure??

**Comment by jcesarmobile** [comment]
Not really sure, I don't configure the locale, so I assume english is the default. On they code or doc they don't confirm the default, just this:
/**
 * Sets the locale to use for speech recognition.
 *
 * Most of the time, the value passed is a ISO country code. To get our supported ISOs, consult "Freeform Dictation Languages" under "Speech Recognition Settings" when viewing details about a specific key.
 */

As it seems the locale can be configured using an ISO code now, I'll update the plugin when I have time to add other languages from javascript.

**Comment by neaGaze** [comment]
how can i use this in phonegap ios project? I have followed this http://www.raywenderlich.com/41377/creating-a-static-library-in-ios-tutorial  process to add, but it is not working. Will you please help me on this?

I am getting the issues like:
Undefined symbols for architecture armv7:
  "_kCFHTTPVersion1_1", referenced from:
      -[ISURLConnection _createHTTPRequest] in libiSpeechSDK.a(ISURLConnection.o)
  "_CFHTTPMessageCreateRequest", referenced from:
      -[ISURLConnection _createHTTPRequest] in libiSpeechSDK.a(ISURLConnection.o)

**Comment by jcesarmobile** [comment]
can you open your own issue for this?

**Comment by jcesarmobile** [comment]
Added multi language support, now all this can be used:

 English (Canada) (en-CA) 	
English (United States) (en-US) 	
Spanish (Spain) (es-ES) 	
French (France) (fr-FR) 	
Italian (Italy) (it-IT) 	
Polish (Poland) (pl-PL) 	
Portuguese (Portugal) (pt-PT)
