### ISSUE TITLE
IOS error Unexpected CFBundleExecutable Key

### ISSUE THREAD

**Issue by frank-2007** [macdonst/SpeechRecognitionPlugin#31]
Thanks for this nice plugin. The Application Loader from Apple returns this error. 

"Unexpected CFBundleExecutable Key. The bundle at 'Payload/Test.app/iSpeechSDK.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist using a CFBundlePackageType of BNOL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

**Comment by jcesarmobile** [comment]
thanks for reporting, I'll check if there is a new iSpeech SDK available and will update the plugin

**Comment by frank-2007** [comment]
Thanks you so much!!

**Comment by jcesarmobile** [comment]
I've just updated iSpeech SDK, let me know if it fixed your issue

**Comment by frank-2007** [comment]
Thank you so much!!!!! It works now!

**Comment by fmbuthia** [comment]
I just tried to submit my app and got the same error, how did you fix it.

**Comment by frank-2007** [comment]
Hi, I use Appery to build my apps, so I don't know much of what happens in the background. I just loaded the updated plugin and the error on submission went away.

I would not make any changes to configuration files (info.plist), others had reported this error for other plugins. The error has to do with changes recently implemented by Apple and it can be solved by some changes in the plugin itself

**Comment by ALSephirot** [comment]
Hi, i have the same error. Somebody help me fix it. Thanks

**Comment by jcesarmobile** [comment]
I've removed the CFBundleExecutable key from the iSpeechSDK.bundle Info.plist to
allow submissions to apple store.

**Comment by carlosjm0325** [comment]
Im unfortunately encountering this same issue now.. latest of cordova, xcode and your plugin... any thoughts?  Same issue and checked bundle info.plist file and theres no key by that name... am I possibly looking in the wrong place?

**Comment by carlosjm0325** [comment]
And quick note, I am able to test the application using xcode when I run test, but when I try to validate or upload to apple to get in my test environment, I get the error mentioned above, preventing me from upload.  Desperately in need of help! :) Please please!

And GREAT GREAT PLUGIN!!! on contrary to what others might think, you've saved my project!

**Comment by jcesarmobile** [comment]
I updated the SDK and forgot to check if iSpeech had already deleted that key, and they haven't... 
I have contacted them and also removed the key for now. Thanks!
