### ISSUE TITLE
IOS Unable to copy asset information

### ISSUE THREAD

**Issue by hsmith825** [macdonst/SpeechRecognitionPlugin#34]
When running SpeechSynthesisUtterance() on IOS 9.1 I get the following error:
|AXSpeechAssetDownloader|error| ASAssetQuery error fetching results (for com.apple.MobileAsset.MacinTalkVoiceAssets) Error Domain=ASError Code=21 "Unable to copy asset information" UserInfo={NSDescription=Unable to copy asset information}

My code is as follows:
var u = new SpeechSynthesisUtterance();
    u.text = wmessage;
    u.lang = 'en-US';
    u.rate = 1.0;
    u.onend = function(event) {

Help is appreciated!!!
Thanks!!!
Howard

**Comment by jcesarmobile** [comment]
This plugin is about speech recognition, SpeechSynthesisUtterance is about text to speech, and it's handled by the webview, not by the code. You can send the bug report to apple
https://developer.apple.com/bug-reporting/using-bug-reporter/

BTW, I tested the code and it's working on my device with iOS 9.2.
