### ISSUE TITLE
ERROR: Method 'stop:' not defined in Plugin 'SpeechRecognition'

### ISSUE THREAD

**Issue by yantsey** [macdonst/SpeechRecognitionPlugin#35]
I don't see any 'stop' method defined in src/ios/SpeechRecognition.m, so my code won't work. I am copying example 3 from here:

https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html#examples

How do I solve this error?

**Comment by jcesarmobile** [comment]
Sorry for not answering before.
I thought I put on the readme that iOS only supports start and onresult right now, but I can't find it, so I might have forgoten
Right now it can be canceled with a native button that appears while the recognition screen is present, but can't be canceled from code yet.
