### ISSUE TITLE
How can I set the speech recognition to a language besides English?

### ISSUE THREAD

**Issue by thadeuszlay** [macdonst/SpeechRecognitionPlugin#38]
I want to use it for an ionic project. I followed this helpful tutorial:
http://devgirl.org/2016/01/08/speaking-with-cordova/#comment-1549581

It successfully recognizes my speech and prints it correctly. But only for the English language. How can I set the **speech-to-text** feature to another language besides English? I even tried to change the java plugin from

    String lang = args.optString(0, "en");

to 

    String lang = args.optString(0, "fr");

also I changed in the file SpeechRecognition.js from

    this.lang = "en";

to 

    this.lang = "fr";

But the speech recognition would always print out English terms.

**Comment by jcesarmobile** [comment]
See https://github.com/macdonst/SpeechRecognitionPlugin/issues/27
