### ISSUE TITLE
Nothing happen...

### ISSUE THREAD

**Issue by stefdelec** [macdonst/SpeechRecognitionPlugin#39]
Hi, 
I don't know if it is the right place but nothing happens and I don't understand why. I'd love to use this plugin. Any help?

I open a thread on stackoverflow. 
http://stackoverflow.com/questions/35089306/speech-to-text-plug-in-phonegap-not-working

Any help?

Thanks

**Comment by jcesarmobile** [comment]
Sorry but the question is really confusing, you are using gap tags, like you were using phonegap build, but you say that you are using phonegap desktop, so you are trying on the phonegap developer app?

You can't run 3rd party plugins on the phonegap developer app, you have to compile your own app
And this plugin can't be used on phonegap build
