### ISSUE TITLE
Speech Recognition on IntelXDK

### ISSUE THREAD

**Issue by keithsptr** [macdonst/SpeechRecognitionPlugin#4]
Hi,

I am developing my HTML5 app using Intel XDK. Is there a way to implement this plugin please?

Thanks

**Comment by jcesarmobile** [comment]
I'm not familiar with IntelXDK, but it should be installed as any other plugin. Tell us more about your problem.

**Comment by keithsptr** [comment]
My problem is that I cannot seem to add the cordova plugin. This software uses HTML5 and then let you build the app as Android, iOS, Windows 8 etc.

**Comment by jcesarmobile** [comment]
Read this: https://software.intel.com/en-us/html5/articles/adding-third-party-plugins-to-your-xdk-cordova-app, the part with "Including Third-Party Plugins" as title
