### ISSUE TITLE
Works on Android 5.0 but not 6.0

### ISSUE THREAD

**Issue by auxdesigner** [macdonst/SpeechRecognitionPlugin#41]
This is my code:
document.querySelector('#btn').addEventListener('click', function () {
            var recognition = new SpeechRecognition();
            recognition.start();
            recognition.onresult = function(event) {
                    if (event.results.length > 0) {
                        recognizedText = event.results[0][0].transcript;
                        alert(recognizedText);
                    }
            };            
});

On 5.0 it works like a charm. On 6.0 click on button won't do anything...

**Comment by Reon90** [comment]
You need to request permission on Android 6.
I realize it
https://github.com/macdonst/SpeechRecognitionPlugin/pull/40

**Comment by auxdesigner** [comment]
@Reon90 Thank you so much! It works now.

**Comment by jcesarmobile** [comment]
I'll reopen until the PR is merged

**Comment by gilles-danjou** [comment]
How do you request permission ?

**Comment by iischwuerfl** [comment]
+1

**Comment by jcesarmobile** [comment]
I've updated the code to handle Android 6 permissions. Closing the issue
