### ISSUE TITLE
Not working Cordova 6 and iOS 9 Emulator 

### ISSUE THREAD

**Issue by ubergeekzone** [macdonst/SpeechRecognitionPlugin#48]
So it's not working on Cordova 6 with iOS emulator... providers no errors.. just click the button and it does nothing... Any ideas?

**Comment by gilles-danjou** [comment]
same problem but with android emulator

**Comment by ubergeekzone** [comment]
try your production key instead of the test key.

On Tue, Mar 15, 2016 at 9:23 AM, Gilles Danjou <notifications@github.com>
wrote:

> same problem but with android emulator
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/macdonst/SpeechRecognitionPlugin/issues/48#issuecomment-196814611
>



-- 

Amy Bridges
Owner
P: (404) 487-6003 ext 700
E: amy.bridges@invoate.com
LinkedIn <https://www.linkedin.com/in/amy-bridges-ab33b336> | Invoate
<http://www.invoate.com> | Behance <https://www.behance.net/ubergeekzone>

**Comment by jcesarmobile** [comment]
Saw your stackoverflow question.
Will check why their demo key doesn't work anymore.
http://stackoverflow.com/questions/35714165/cordova-speech-recognition-plugin

**Comment by ubergeekzone** [comment]
*Pat* replied     Apr 7 3:20am 
      Thanks for letting us know Amy,

Nothing received here but will keep our eyes open.

Best regards,

Pat 
 --
Pat Murphy
support@teamwork.com
Support  
      
      *Amy Bridges* asked    Apr 6 11:37pm 
      Hello, 

 My account was hijacked earlier today, if you have something form me
about a proposal agreement do not open it. I have took the appropriate
measures to ensure this will not happen again. 

Thanks

-- 

Amy Bridges

Owner
P: (404) 487-6003 ext 700
E: amy.bridges@invoate.com <mailto:amy.bridges@invoate.com>
LinkedIn
<https://t.yesware.com/tt/24554823f0769e3928dc2ff821448567077d1807/cc7947eb285eaae542a5318d220bf049/afeb9aa266b28974e84e4d1ad30e3c37/www.linkedin.com/in/amy-bridges-ab33b336>
| Invoate
<http://t.yesware.com/tt/24554823f0769e3928dc2ff821448567077d1807/cc7947eb285eaae542a5318d220bf049/7afd6d954dbb7c577d195f10610bebf1/www.invoate.com>
| Behance
<https://t.yesware.com/tt/24554823f0769e3928dc2ff821448567077d1807/cc7947eb285eaae542a5318d220bf049/f1e0e013a0c812229189b26c95d207f1/www.behance.net/ubergeekzone>

 

 
      
     
{"TWDESKMessageId":"t!84424953!u41294!1!79500560-981c-4f21-98a2-249149d12ff6*teamworkdesk!com"}
 
   Powered by Teamwork Desk <https://www.teamwork.com/desk>

**Comment by jcesarmobile** [comment]
Just tested the default demo key ("developerdemokeydeveloperdemokey") and worked fine on device and simulator, closing issue.
