### ISSUE TITLE
Speech Recognition fails on Android if the "Ok Google" function to every screen is activated

### ISSUE THREAD

**Issue by fretman92** [macdonst/SpeechRecognitionPlugin#49]
Hello,

First, thanks for this great plugin. I use it on both iOS and android.

Second, I'd like to report a bug I encounter since I updated my Nexus 7 to Marshmallow.
The ["Ok Google" function on every screen](http://www.howtogeek.com/213784/how-to-turn-off-ok-google-on-your-android-device/) is ON by default.

Besides the privacy problem, it seems this feature causes the `RecognitionListener` to throw a ERROR_NO_MATCH (code 7) directly (about 20ms) after start
![capturespeech](https://cloud.githubusercontent.com/assets/305637/13458827/0504eb00-e070-11e5-8cdc-071b2af1fc5a.PNG).

So I'd like to share the following **workaround** with you: http://stackoverflow.com/a/31346373/1835270

Do you guys think it could be added to this plugin?

Other **idea**: https://code.google.com/p/android/issues/detail?id=179293

**Comment by jcesarmobile** [comment]
I was having the same problem but I didn't have the "Ok Google" on every screen activated.
This issue looks like this one: https://github.com/macdonst/SpeechRecognitionPlugin/issues/50

I think I've fixed it, can you check?

**Comment by fretman92** [comment]
You're talking about https://github.com/macdonst/SpeechRecognitionPlugin/commit/ec84e6f048c59fcd7a2531a30034f61ef5297d4c? 
Yes, that's exactly the patch I implemented, works perfectly now. The only problem is that I cannot install 1.0.1 version, so I'll stick with my local edits for now :/
Thanks for the support anyway. Issue can be closed :tada:

**Comment by jcesarmobile** [comment]
Why can't you install it? getting any error?

**Comment by fretman92** [comment]
Install crashed a while ago with VS2015, but tried again with cordova CLI just now, and it worked. So problem auto solved, I can now enjoy the latest version. Thanks for helping :+1:

**Comment by jcesarmobile** [comment]
Ah, yeah, I fixed the VS2015 bug too.
