### ISSUE TITLE
enable other language in ios

### ISSUE THREAD

**Issue by neaGaze** [macdonst/SpeechRecognitionPlugin#5]
How can i enable other language in ios?

**Comment by jcesarmobile** [comment]
Now the plugin supports this languages:

 English (Canada) (en-CA) 	
English (United States) (en-US) 	
Spanish (Spain) (es-ES) 	
French (France) (fr-FR) 	
Italian (Italy) (it-IT) 	
Polish (Poland) (pl-PL) 	
Portuguese (Portugal) (pt-PT)


To set the language use this code
```
var recognition = new SpeechRecognition();
recognition.lang = "es-ES";
 ```
two-charater codes can be used to, but "en" will use "en-US"

**Comment by vko-online** [comment]
Why not russian?

**Comment by jcesarmobile** [comment]
because the plugin uses iSpeech SDK and those are the languages iSpeech SDK supports (last time I checked)
