### ISSUE TITLE
The second start Recognition go to Error Function

### ISSUE THREAD

**Issue by Fraendal** [macdonst/SpeechRecognitionPlugin#50]
Hello, I work on an app with cordova but recently i am having some difficulties with this plugin, one out of two times go to the error function, but i can listen the "start recognition" sound.

I tried with a new Cordova Project with only the plugin but same result.

The last week i didn't got this problem.

Anyone can help me ?
(Sorry for my english)

**Comment by Avishay116** [comment]
Same problem here..

**Comment by jcesarmobile** [comment]
I've updated the code, can you see if you can reproduce the issue?

**Comment by kaeverens** [comment]
that's working for me now. wasn't working in 0.1.0
