### ISSUE TITLE
onError handling(ERROR_NO_MATCH or ERROR_SPEECH_TIMEOUT)

### ISSUE THREAD

**Issue by peepsilog** [macdonst/SpeechRecognitionPlugin#52]
First of all cooool plugin.Thanks!

The plugin has been implemented within an ionic app but it needs a handler when a users says nothing or no speech detected in **Android** platform. Upon tweaking with the plugin, the error received on "onError" has been isolated to "ERROR_NO_MATCH"(if the speech to text hears the background noise) and "ERROR_SPEECH_TIMEOUT"(if there are no sounds received within the plugin).

Now for the question: Is it possible to pass an indicator coming from the SpeechRecognition.java file within the "onError" function so that we can identify it when we call it within our app?Thanks!

**Comment by jcesarmobile** [comment]
It's possible, but it's not implemented

See https://github.com/macdonst/SpeechRecognitionPlugin/issues/10

**Comment by peepsilog** [comment]
Oh i see, will try to implement. Thanks @jcesarmobile  for the quick reply and for the fix a few hours ago for the "onError called the second time you call start"!

**Comment by LoicMoerman** [comment]
Hello, did you find a solution ? Thank you
