### ISSUE TITLE
Speech recognition not running in Android version 4.4.4 KTU84P 

### ISSUE THREAD

**Issue by mailmrmanoj** [macdonst/SpeechRecognitionPlugin#58]
Ionic Info:
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:Node Version: v4.2.3

As you see these are the versions of depedencies used to create an app in ionic.But  as soon as I open the app it says 'Unfortunately the app has stopped' and gets closed.
Android version 4.4.4 KTU84P is my phone's android version.

**Comment by jcesarmobile** [comment]
Please, don't create new issues, continue on the other one you already created 
https://github.com/macdonst/SpeechRecognitionPlugin/issues/56
