### ISSUE TITLE
Does it support Arabic in Android

### ISSUE THREAD

**Issue by islamoc** [macdonst/SpeechRecognitionPlugin#59]
Hello
Does this Plugin support other languages like Arabic in Android

Thank you

**Comment by jcesarmobile** [comment]
Yes, it supports different languages.
But, sadly, google doesn't provide information about which languages it supports (Or I didn't find that information anywhere)

Try setting the recognizer language like this:
`recognition.lang = "ar";`
or 
`recognition.lang = "ar-EG";`

if it's not supported it should call the error callback with an error code 7

**Comment by islamoc** [comment]
Hello
Thank you for the quick response
I'm using the web speech API on chrome and I'm using ar-QR and it is
working just fine
Very interesting project I would definitely contribute when I have spare
time

**Comment by macdonst** [comment]
@islamoc yeah, Android supports speech rec using Arabic which the plugin is built on top of. I'm going to close this for now. Re-open if you encounter problems.
