### ISSUE TITLE
angular module implementation

### ISSUE THREAD

**Issue by moisesd37** [macdonst/SpeechRecognitionPlugin#6]
I've spent a lot of time trying to figure out how to make this work on an angular module for an ionic app, any ideas?

**Comment by romanrast** [comment]
same here.. does someone managed to implement this in an ionic ios app?

**Comment by moisesd37** [comment]
@romanrast i've got this working on an ionic android app:

<script type="text/javascript">
var recognition;
document.addEventListener('deviceready', onDeviceReady, false);

function onDeviceReady() {
    recognition = new SpeechRecognition();
    recognition.onresult = function(event) {
        if (event.results.length > 0) {
            q.value = event.results[0][0].transcript;
            q.form.submit();
        }
    }
}
</script>
<form action="http://www.example.com/search">
    <input type="search" id="q" name="q" size=60>
    <input type="button" value="Click to Speak" onclick="recognition.start()">
</form>

is the code from the example. You don't need anything else.
but i think for troubleshooting on ios @jcesarmobile  is the right person to help you.

**Comment by romanrast** [comment]
ok nice to here. 
What did you do to implement the plugin?
I tried cordova plugin add https://github.com/macdonst/SpeechRecognitionPlugin on the root folder. But it doesn't seem to work for me.

Did you do anything else?

**Comment by moisesd37** [comment]
no, to install, open command line, navigate to your project's root folder and install the plugin:
cordova plugin add https://github.com/macdonst/SpeechRecognitionPlugin

Then include the example above in your index.html file

Note: in won't work on your browser, you have to run: 
ionic platform add android
and
ionic build android

then install on your device (connected to any network)

**Comment by jtanori** [comment]
This is what I have for just doing a basic recognition, It can be used as service but I just put this piece of code as a prototype of what I just started building:

````JS
angular.module('dct2.controllers', [])

.controller('DashCtrl', function($scope, $ionicPlatform, $timeout) {
    $scope.recognition = undefined;
    $scope.transcript = '';
    $scope.hyphenatedTranscript = '';
    $scope.h = new Hypher(HypherLanguages.spanish); 

    $scope.hyphenate = function(transcript){
        //Check for multiple words (paragraph)
        transcript = transcript.split(' ');
        transcript = transcript.map(function(w){
            return $scope.h.hyphenate(w);
        });

        $scope.hyphenatedTranscript = transcript;
    };

    $ionicPlatform.ready(function(){
        $scope.recognition = new SpeechRecognition();
        $scope.recognition.lang = 'es-ES';//Set to spanish
        //TODO: Add multilingual support
        $scope.recognition.onresult = function(event) {
            if (event.results.length > 0) {
                $timeout(function(){
                    $scope.$apply(function(){
                        $scope.transcript = event.results[0][0].transcript;
                        $scope.hyphenate($scope.transcript);
                    });
                });
            }
        }
    });

});
````

**Comment by jcesarmobile** [comment]
I've read this blog post that uses this plugin on an ionic project, hope it helps

http://devgirl.org/2016/01/08/speaking-with-cordova/

BTW, I'm closing the issue as it's not a real issue with the plugin itself
