### ISSUE TITLE
Remove pause before result

### ISSUE THREAD

**Issue by kmcq** [macdonst/SpeechRecognitionPlugin#62]
Hello, great plugin! I am wondering if anyone else experiences a long pause after speech has stopped and before the onresult callback is fired. The pause is about 5 seconds long. I have tried editing the java code and setting the `EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS` field but that does not shorten this pause. Is there a way to shorten this pause?

**Comment by demcoderseinnachbar** [comment]
Hi, yes i am facing the same problem. And this is really annoying because i intend to use the plugin to recognize commands. But right now you habve to wait a long time before you command is executed 😞 So i hope anybody has an idea how to reolve this issue!

**Comment by demcoderseinnachbar** [comment]
Does pull request #61 partial results resolves this issue?

**Comment by jrlandau** [comment]
Hi, I am having the same problem.  I also have a web app that uses the Web Speech API, which appears to be very similar--actually nearly word for word.  Same functions, same events.  Strangely, when running this app in the Chrome browser on the same Android phone, with the same speech examples, there is minimal delay in receiving the onresult event.

Also, I have run the example found [here](http://devgirl.org/2016/01/08/speaking-with-cordova/), without any changes, and it gets the same result--about a 6 sec recognition delay.

**Comment by htsnet** [comment]
It is happening now, but it is a new situation. Just a few days ago this time is very short. I don´t know what happened.

**Comment by r4nm4** [comment]
Hi everyone,
first of all, thank you for this great plugin!
Any news about this "annoying" issue?
Thank you so much

**Comment by Aerowalk** [comment]
Could this be the issue?
http://stackoverflow.com/questions/38150312/google-speech-recognition-timeout

**Comment by jcesarmobile** [comment]
Yes, it's a bug on Google Now

**Comment by kmcq** [comment]
Thanks @Aerowalk! That seems to be the issue.

Looks like some people are getting somewhat passable results by requesting partial results. Their solutions feel hacky to me though so I wouldn't suggest those for this plugin. Hopefully Google fixes this soon..

Closing this since it's not a problem with the plugin.

**Comment by r4nm4** [comment]
Hi All,
Definitely is Google bug, if you uninstall all the GoogleNow app update, everything work great!

But can I ask your help to implement this "BugRecognitionListener" (https://gist.github.com/brandall76/bbf908d886c9a3469e6957812555f1f7) into this great plugin?

Maybe just a temporary branch.
Or if someone could be so kindness and send me the "SpeechRecognition.java" file with this patch.

Thank you and I'm sorry if I re-opened this ticket.
Thanks!
