### ISSUE TITLE
remove the beep sound before and after recording

### ISSUE THREAD

**Issue by mathieu21** [macdonst/SpeechRecognitionPlugin#63]
Is this something we could do on the plugin or it is something forced by android ?

**Comment by apuravchauhan** [comment]
This is not an issue with plugin. Check this out if you want to add this custom behaviour:
https://github.com/galrom/ContinuesVoiceRecognition

**Comment by texano00** [comment]
Hi, is this issue closed?
I'm using this plugin in an Ionic v.3 app, working very well on both platform (IOS,Android).
I've the same "problem" of @mathieu21, on Android i'd like to remove thee beep sound on start and end recognition (same sound of Google Assistant). 
On the other hand on IOS no sounds is played automatically that is the behaviour that i expect.

I've read the @apuravchauhan workaround, so we need to write Java code? There's no solution to remove beep sound with this PhoneGap plugin?

Thanks

**Comment by PragmaticEd** [comment]
It's been 2 years... How can one fix this?

**Comment by jcesarmobile** [comment]
It's not a bug, it's a "feature", sorry, we can't do anything about it
