### ISSUE TITLE
Recognition.stop() work only at first Recognition.start()

### ISSUE THREAD

**Issue by mosca90** [macdonst/SpeechRecognitionPlugin#65]
In my app (ionic2 with cordova plugin), there are 2 buttons:
- The first one, call a function that contain **recognition.start()**
- The second one, call a function that contain **recognition.stop()**

After the first **.start()** event, i can **.stop()** it with no issues, and get the correct text back.

The second time, when I try to **.stop()** my recognition after the **.start()**, I get an error, the recognition does not stop and the text back has some delay, like 10sec.

I tried using recognition.stop() and recognition.abort() methods. But it didn't work.
Someone knows why?

**Comment by mosca90** [comment]
Ok, after some reading, i found that the problem is **Google Now**.
If you uninstall updates (and use version 5 for example), all work great, without using **recognition.stop()** and giving text back after 1sec max from speech end.

Are there some workaround to avoid uninstalling **Google Now** updates and maintain the proper functioning?

Thx.

**Comment by jcesarmobile** [comment]
I don't think so, let's hope they fix this issues on next release of Google Now...

**Comment by mosca90** [comment]
So sad, unistalling updates for developing test, waiting for Google.
Thx. @jcesarmobile
