### ISSUE TITLE
Android - SpeechRecognizer takes a long time to stop listening

### ISSUE THREAD

**Issue by joshglazer** [macdonst/SpeechRecognitionPlugin#67]
I've recently started having an issue with the SpeechRecognizer taking around 5 seconds to stop listening after I stop speaking into the phone.  Has anyone else had any issues with this and have a way to fix it?

I'm using Android V6.0.1

I'm seeing people with similar issues here but they are probably not using this plugin:
http://stackoverflow.com/questions/38150312/google-speech-recognition-timeout

Thanks!

**Comment by YDamree** [comment]
Up please
I have the same issue :(

**Comment by jcesarmobile** [comment]
It's a Google bug, you can read more on https://github.com/macdonst/SpeechRecognitionPlugin/issues/62
