### ISSUE TITLE
SpeechRecognitionPlugin iOS

### ISSUE THREAD

**Issue by rakeshkathoju** [macdonst/SpeechRecognitionPlugin#78]
Hi,
Dose it supports Arabic language in iOS phone gap , i need support for Arabic text to speech. 
if not can you please help me which plugin supports Arabic speech

**Comment by jcesarmobile** [comment]
This plugin is for speech recognition (speech to text), not for text to speech.
For text to speech you can try https://github.com/macdonst/SpeechSynthesisPlugin, but I don't know if it supports Arabic

**Comment by rakeshkathoju** [comment]
Hi  jcesarmobile ,
Speech recognition to fill a text area, i wrote the following code will it support Arabic.
           var recognition = new SpeechRecognition();
             recognition.lang = 'ar-SA';
           recognition.rate = 1.2;
            recognition.start();
            recognition.continuous = true;
            recognition.onresult = function (event) {            
            for (var i = 0; i < event.results.length; i++) {
            $('#ninput').val(event.results[i][0].transcript);
            $('#skinput').val(event.results[i][0].transcript);
            }
            }
if i didn't set any language it is printing in english.  I need Arabic. language to fill text area.can you please help me in setting arabic language to fill text area.

// and For reading text I wrote following code it is speaking in arabic. which is working fine.
 var utterance = new SpeechSynthesisUtterance();
            utterance.text = 'لرجاء الإتصال بشبكة الإنترنت';
            utterance.lang = 'ar-SA';
            utterance.rate = 1.2;
            utterance.onend = function(event) {
            }
            speechSynthesis.speak(utterance);


//Fot this i used Following plugin :-  cordova plugin add https://github.com/macdonst/SpeechRecognitionPlugin .

**Comment by jcesarmobile** [comment]
The plugin uses [iSpeech](http://www.ispeech.org/) SDK to to de speech recognition and they don't support Arabic at the moment.
You can contact them and ask for Arabic support.

**Comment by rakeshkathoju** [comment]
Okay, Thank you

**Comment by pratikq23** [comment]
> Okay, Thank you

Can you tell me how you use this plugin in ios. Because i'm getting error speechrecognition can't found.
