### ISSUE TITLE
confidence

### ISSUE THREAD

**Issue by asteckles** [macdonst/SpeechRecognitionPlugin#79]
Great plugin.  How can I get the confidence level of each recognition?  Thanks.

**Comment by NBAMj** [comment]
@asteckles As simple as: `event.results[0][0].confidence`
In case you want to have the result with the highest confidence ratio, loop through the array and compare their confidence level.

Hope this helps :smile:

**Comment by jcesarmobile** [comment]
closing as it's a question and was answered
