### ISSUE TITLE
Gives weird output

### ISSUE THREAD

**Issue by hybridapp20161** [macdonst/SpeechRecognitionPlugin#80]
Hi,
We are using your plugin for speech recognition to develop cordova ios app.
All things working fine but it gives weird output(doesnt recognize speech input properly) .
We have implemented this line for US english then too it does not recognize speech correctly.
(recognition.lang="en-US").
Do we need to change somewhere else to set language preference.

Environment which we are using:
cordova: 6.3.1
iOS device: iPhone5(iOS 10.1.1)(14B100)
IOS:OS X EI Capitan..10.11.6 (15G1004)

Kindly help.
Thanks in advance.

**Comment by jcesarmobile** [comment]
This might be a limitation of iSpeech.

Try latest version, it now uses SFSpeechRecognizer on iOS 10 and should return better results
