### ISSUE TITLE
Can't disable the iSpeech popup on ios?

### ISSUE THREAD

**Issue by williamtay7** [macdonst/SpeechRecognitionPlugin#82]
I need to disable the iSpeech popup. 

Will you be going to change from iSpeech to Siri?

**Comment by jcesarmobile** [comment]
You can't disable the iSpeech popup, I think you can remove the iSpeech brand if you pay.

I'm considering using the iOS 10 native speech recognition on the plugin, but it's only supported on iOS 10, so iSpeech should remain for iOS 9 and earlier.

**Comment by macdonst** [comment]
@jcesarmobile the sirikit stuff added in iOS 10 only allows you to add voice paths to you app into Siri. AFAIK there is no general purpose speech recognition API for iOS 10 from Apple. Another though I had was trying the IBM Watson speech rec.

**Comment by jcesarmobile** [comment]
It's not sirikit, they included a speech recognizer on iOS 10
https://developer.apple.com/reference/speech/sfspeechrecognizer

**Comment by macdonst** [comment]
@jcesarmobile Wow, I did not hear about that class anywhere. We should create an issue to explore this. I kinda want to do it right now but it's time for me to look at FCM.

**Comment by jcesarmobile** [comment]
I thought I tweeted it after the WWDC, but just checked and I didn't
I tested the sample project and worked really well 
https://developer.apple.com/library/content/samplecode/SpeakToMe/Introduction/Intro.html
