### ISSUE TITLE
ios vioce recognition grammer mistakes

### ISSUE THREAD

**Issue by harishkesari** [macdonst/SpeechRecognitionPlugin#85]
ios device is not recognition is voice grammar correctly. when ever we speak Philips it fetches Philippines. we set the language as'en-US'. checked with the web it works perfectly good.  only problem with ios device need the alternative solutions.

**Comment by jcesarmobile** [comment]
Sadly there is nothing we can do about this, the result is provided by iSpeech SDK.
I want to use in the plugin the native iOS speech recognition included in iOS 10, that might improve the speech recognition on iOS 10 devices
