### ISSUE TITLE
plugin not available on Adobe Phonegap Plugin List (not accessible from DevExtreme)

### ISSUE THREAD

**Issue by Tawsif** [macdonst/SpeechRecognitionPlugin#9]
Hi, 

I am developing DevExtreme Application which supports plugins only from https://build.phonegap.com/plugins (Adobe Phonegap Build).
 
Hence it a request to register/submit your plugin to https://build.phonegap.com/plugins, so that I can use it, 

Thanks in advance :)

**Comment by jcesarmobile** [comment]
To publish plugins in phonegap build you need a paid phonegap build account, I don't have one, maybe @macdonst have.

Anyway, as DevExtreme is a paid product, I think you should contact them and tell them they should support npm and plugins.cordova.io plugins too, as it's free to publish plugins there (phonegap build already supports them)

**Comment by jcesarmobile** [comment]
Somebody forked this plugin and uploaded it to phonegap build
https://build.phonegap.com/plugins/3966
