### ISSUE TITLE
Is the android and iOS APIs used in this plugin is free for commercial use?

### ISSUE THREAD

**Issue by kauspatel** [macdonst/SpeechRecognitionPlugin#95]
I understand the plugin comes under MIT license but the apis used inside for connecting to remote server for speech recognition in Android and iOS, are free for commercial use or not.
Will Google for Android or Apple for iOS charge something for speech recognition as we connect to their remote server using dedicated speech api of android and iOS.

**Comment by jcesarmobile** [comment]
Right now on Android it uses `SpeechRecognizer`, which is native and free to use.
On iOS 9 and older it uses iSpeech. It used to be free for mobile apps, but not sure anymore according to their pricing plans page. https://www.ispeech.org/developer/purchase/plans
On iOS 10 and newer it uses `SFSpeechRecognizer`, which is native and free to use.

Neither Google for the `SpeechRecognizer` nor Apple for the `SFSpeechRecognizer` charge money for them at the moment, but I can't assure they will in the future.
