### ISSUE TITLE
'Speech/Speech.h' file not found

### ISSUE THREAD

**Issue by philiv99** [macdonst/SpeechRecognitionPlugin#96]
Encountered the following error when compiling plugin using Microsoft Visual Studio taco-remote build:

Plugins/org.apache.cordova.speech.speechrecognition/SpeechRecognition.h:3:9: fatal error: 'Speech/Speech.h' file not found
1>  #import <Speech/Speech.h>
1>          ^
1>  1 error generated.
1>
1>  ** BUILD FAILED **

**Comment by jcesarmobile** [comment]
Probably a taco bug, going to close, I can't reproduce on macOS and Speech framework is linked here https://github.com/macdonst/SpeechRecognitionPlugin/blob/master/plugin.xml#L90
